---
- hosts: app
  gather_facts: no
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Copy your flask app file to the Vagrant servers
    copy:
      src: /$PWD/app.py
      dest: /home/vagrant/app.py
  - name: installing pip3
    apt:
      name: python3-pip
      update_cache: yes
  - name: Installing flask module
    pip:
      executable: pip3
      name: flask
      state: latest
  - name: install cassandra lib
    pip:
      executable: pip3
      name: cassandra-driver
      state: latest
  - name: run flask app
    shell: |
      nohup python3 app.py > log.txt 2>&1 &
