---
- hosts: db
  gather_facts: no
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: install Java Repo
    apt_repository: repo='ppa:openjdk-r/ppa' 
  - name: update Cache
    apt: update_cache=yes
  - name: install Java
    apt: name=openjdk-8-jdk state=present
  - name: add cassandra repo
    shell: echo "deb http://downloads.apache.org/cassandra/debian 40x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - name: add key
    ansible.builtin.apt_key:
      url: https://downloads.apache.org/cassandra/KEYS
      state: present  
  - name: update Cache
    apt: update_cache=yes
  - name: 
    apt:
      name: cassandra
      state: present
  - name: update rpc address
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: 'rpc_address: localhost'
      replace: "rpc_address: 0.0.0.0"
  - name: update broadcast rpc address
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: '# broadcast_rpc_address: 1.2.3.4'
      replace: "broadcast_rpc_address: 192.168.10.11"
  - name: reload daemon
    command: systemctl restart cassandra
  - name: pause for reload
    pause:
      minutes: 1
  - name: create keyspace
    shell: cqlsh -e "CREATE KEYSPACE IF NOT EXISTS Test WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};"
  - name: create table
    shell: cqlsh -e "create table if not exists test.test (ts timestamp primary key);"
